### PR TITLE
Fixes backspace gui input bug

### PR DESCRIPTION
**Pull request by magnusviri**
Fixes Issue 210 (https://github.com/alesan99/mari0_ae/issues/210).

### CODE REVIEW

**Comment by WilliamFr0g** [comment]
I already fixed this in the text highlighting pull request, so that one gets merged then this shouldn't be necessary

**Comment by magnusviri** [comment]
Cool beans. Should I close this?

**Comment by WilliamFr0g** [comment]
Probably yeah

**Comment by alesan99** [comment]
0e51914a0a994f900192525b07b8466516c0acfb

**Pull request closed without merging**
