### PR TITLE
Physics Improvements

### PR DESCRIPTION
**Pull request by WilliamFr0g**
Fixes bugs with semisolids colliding incorrectly and poor detection of falling objects

### CODE REVIEW

**Comment by WilliamFr0g** [comment]
I have some changes wip, don't merge until I finish

**Comment by WilliamFr0g** [comment]
Ok i did it

**Comment by WilliamFr0g** [comment]
Addresses #63

**Comment by alesan99** [comment]
WIP being added 474b4e6504429d5873d54bee61c43b8d706ae7b1

**Comment by alesan99** [comment]
047fc84145ae4f668d701d206986e7e2d7ccd826 should be done

**Pull request closed without merging**
