### PR TITLE
Better Hammer Bros

### PR DESCRIPTION
**Pull request by WilliamFr0g**

### CODE REVIEW

**Comment by alesan99** [comment]
I would encourage the use of more variables (like groundfreezetime).

**Comment by WilliamFr0g** [comment]
Global variables in variables.lua is very annoying. It just means you have to do more looking to find them: first you have to check the actual enemy lua to find the variable name or if it's there at all, then go fishing in the sea that is variables.lua

**Comment by alesan99** [comment]
> Global variables in variables.lua is very annoying. It just means you have to do more looking to find them: first you have to check the actual enemy lua to find the variable name or if it's there at all, then go fishing in the sea that is variables.lua

Consistency is nice
And its not much of an issue with a ctrl f and a good IDE

**Comment by WilliamFr0g** [comment]
I don't use a good ide, I use notepad and 7zip and it's constantly painful. What even is the point? It's a 1.6 thing and 1.6 is full of terrible choices

**Comment by qixils** [comment]
Using constant variables is just good programming practice to A) help annotate your code / make it more clear what it's doing, and B) so if you decide later you want to change fireball speed or whatever then you can easily do that. You don't have to store them in variables.lua, putting them at the top of hammerbro.lua would be fine as well imo.

**Comment by alesan99** [comment]
> I don't use a good ide, I use notepad and 7zip and it's constantly painful.

And I think the solution is obvious here

**Comment by WilliamFr0g** [comment]
Having them as local variables is fine, it's having them in variables.lua that I find problematic. Variables.lua is full of numbers or other constants that are only used one single time, it has no benefit over having them near the usage and only makes finding them take extra steps, even with an IDE. Also I don't think the obvious solution to "the code is hard to read" is the equivalent of "use a magnifying glass"

**Comment by alesan99** [comment]
No one is really questioning whether or not mari0s code is bad and disorganized. If we were starting over sure but it's not worth the time or potential oversights changing it at this point, so might as well try to stay consistent so you at least know the variables will probably be in variables.lua
In vscode I can just search for it instantly throughout all files in the same time it would take me to look at the local variables so hardly an issue for me at least

**Comment by WilliamFr0g** [comment]
There, it uses variables, and also I fixed a bug (which I knew about, but I was too lazy to do before this had any more attention)

**Comment by WilliamFr0g** [comment]
Bumping this to remind people of the current state of bros in this game

ice bro

https://github.com/user-attachments/assets/c9bc17fc-40f1-42f1-8287-8da051226453

**Review by qixils — APPROVED** [review]
Cleaned up variables (they're used a little bit more, and there's no longer unused global variables), updated to LÖVE 11, and fixed some bugs; LGTM

**Pull request merged**
